### ISSUE TITLE
localhost.aws_ssh_keys role public IP failure?

### ISSUE THREAD

**Issue by decmaxn** [bonovoxly/playbook#7]
bastionhost.yml includes localhost.aws_ssh_keys role to add lines into known_hosts file for each ec2 instance with their private and public IP addresses.  This is necessary for other roles like ubuntu.raw_install_python later on. I run into problems with public IP addresses, and private IPs are OK. 

After modify the line parameter of lineinfile task, which import SSH public keys for public IP addresses, the problem disappear. 

Here is the line I refer to:
line: "{{ item.0.public_dns_name}} ecdsa-sha2-nistp256 {{...

Here is what I have changed to:
line: "{{ item.0.public_dns_name}},{{ item.0.public_ip_address }} ecdsa-sha2-nistp256 {{...

**Comment by bonovoxly** [comment]
Added your changes.  Thanks for the input!

(link to commit: https://github.com/bonovoxly/playbook/commit/bcb9683d039b9e8c3a092d5778d12fe2c608a3a5)
