### ISSUE TITLE
.ssh/config file has wrong public IP address when bastionhost is created

### ISSUE THREAD

**Issue by decmaxn** [bonovoxly/playbook#8]
bastionhost.yml will use role aws.bastionhost to create a bastionhost ec2 with elastic IP address attached.  Role localhost.bastion_ssh_config will modify .ssh/config file, but in my test, it wrote a different public IP than the elastic IP. However, the 2nd time run it will fix it. 

I guess the "wrong" IP address come from the public IP when the ec2 instance was created, but later on it is replaced by elastic IP.  That explains why it fixed itself after the 2nd run. 

I appreciate for your great work!

**Comment by bonovoxly** [comment]
Wanted to let you know I haven't forgotten about this; I'll take a look at it as soon as I get the chance.

Thank you for the feedback...

**Comment by decmaxn** [comment]
Just noticed this is still open, I forgot it long time ago. I have taken the walk around of turning it off. I have to remember to turn it on later, but it's works, and easier.  I have got a lot of help from you, and I appreciate.

**Comment by bonovoxly** [comment]
EEEP, sorry about that. I may circle back and revisit this....
