### ISSUE TITLE
Get SSH public key from AWS System Log sometimes fail

### ISSUE THREAD

**Issue by decmaxn** [bonovoxly/playbook#9]
I know it is marked as "this is BEST EFFORT.  May miss the SSH public key", but recently it happens very often to me to the point I have to comment it out. I don't see any body bring it up, is there already a solution or walk around I have missed? Thank you.

**Comment by bonovoxly** [comment]
Sometimes, if you run the playbook too soon after creating the instance (as some of my older playbooks did), the AWS System Log will not be created/will not exist yet.  It can take up to a couple minutes before the log appears.

I generally now 1) Terraform instances/infrastructure and then 2) run the Ansible playbook a few minutes later, giving the AWS System Log time to be created.

A couple follow up questions:

Can you tell me what playbook you are running? 
Is there an actual error, or is the playbook just quietly passing this task?

**Comment by decmaxn** [comment]
It is  playbook/roles/localhost.aws_ssh_keys/tasks/main.yml. 
There is no error messages, it just happily passing through with empty string registered I believe, because lines missing the key is added to the known_hosts file.

If I just run the aws command manually, with vars replaced by the actual value, and the sed and staff, it  shows exactly the key string. Here is the output, I couldn't see anything wrong with it. 

changed: [localhost] => (item={u'kernel': None, u'instance_profile': {u'id': u'AIPAIUU3OWXQIJH6SQWR2', u'arn': u'arn:aws:iam::738882748518:instance-profile/tomcatapi_stg-role'}, u'root_device_type': u'ebs', u'private_dns_name': u'ip-10-100-30-126.us-west-2.compute.internal', u'spot_instance_request_id': None, u'source_destination_check': u'true', u'id': u'i-02c7507b5ddb14ee9', u'ebs_optimized': False, u'state': u'running', u'client_token': u'', u'virtualization_type': u'hvm', u'ramdisk': None, u'public_ip_address': None, u'block_device_mapping': [{u'status': u'attached', u'volume_id': u'vol-05201294a8c08bb0c', u'delete_on_termination': True, u'attach_time': u'2017-10-24T19:27:28.000Z', u'device_name': u'/dev/sda1'}], u'key_name': u'aws-rp-test-key', u'interfaces': [{u'id': u'eni-4591a075', u'mac_address': u'06:b5:a5:61:d8:7e'}], u'image_id': u'ami-746aba14', u'groups': [{u'id': u'sg-2f5a2a52', u'name': u'tomcatapi_stg-inbound'}, {u'id': u'sg-9cb4dae1', u'name': u'bastionhost_stg-inbound_internal'}], u'public_dns_name': u'', u'requester_id': None, u'tags': {u'Environment': u'stg', u'Type': u'tomcatapi', u'Role': u'stg-internal_system', u'Name': u'tomcatapi_stg', u'Organization': u'lab'}, u'monitoring_state': u'disabled', u'placement': {u'tenancy': u'default', u'zone': u'us-west-2a'}, u'ami_launch_index': u'0', u'hypervisor': u'xen', u'region': u'us-west-2', u'launch_time': u'2017-10-24T19:27:27.000Z', u'persistent': False, u'architecture': u'x86_64', u'private_ip_address': u'10.100.30.126', u'vpc_id': u'vpc-5b85d73d'})

**Comment by decmaxn** [comment]
It is playbook/roles/localhost.aws_ssh_keys/tasks/main.yml.
There is no error messages, it just happily passing through with empty string registered. 
If I just run the aws command manually, with vars replaced by the actual value, and the sed and staff, it shows exactly the key string.  So I run debug and found more details: 
 "stderr": "\nAn error occurred (AuthFailure) when calling the GetConsoleOutput operation: Authorization header or parameters are not formatted correctly.", 

Your command has been converted to : "cmd": "aws ec2 get-console-output blabla --output text | sed -n 's/^.*\\(ecdsa-sha2-nistp256 \\)\\(.*\\)/\\2/p' | tail -n 1 | awk '{print $1}' | awk '{print substr($0,1,140)}'". with all the double back slashes.

**Comment by bonovoxly** [comment]
Note that this iterates through hosts gathered by `ec2_facts`:

```
  with_items: "{{ ec2_facts.instances }}"
```

Which I get from this role: https://github.com/bonovoxly/playbook/tree/master/roles/aws.ec2_facts

The `localhost.aws_ssh_keys` role requires the output from the Ansible module, `ec2_remote_facts`.

Are you running your own playbook, or one of mine?

**Comment by decmaxn** [comment]
I am using your ec2_facts role. It does get all the ec2 instances, and I can prove it by debugging the {{ ec2_facts.instances }}. 

I apologize the confusion due to that I have mistakenly pasted the code as is, instead of "insert code", so github rendered double back slashes into one. Let me do it again here: 
The shell command in localhost.aws_ssh_keys is: 
`aws ec2 get-console-output \
           --region {{ vpc.region }} \
           --instance-id {{ item.id }} \
--output text | sed -n 's/^.*\(ecdsa-sha2-nistp256 \)\(.*\)/\2/p' | tail -n 1 | awk '{print $1}' | awk '{print substr($0,1,140)}'`

but as shown in output of my debug, it has been converted to the following with back slashes doubled.
`"cmd": "aws ec2 get-console-output blablabla --output text | sed -n 's/^.*\\(ecdsa-sha2-nistp256 \\)\\(.*\\)/\\2/p' | tail -n 1 | awk '{print $1}' | awk '{print substr($0,1,140)}'"`

That causes the "Authorization header or parameters are not formatted correctly." error , but I don't know why the command is been changed on the fly.

**Comment by bonovoxly** [comment]
Oh, OK, interesting, this seems like some misconfigured AWS credentials.

Some possible things to check are Ansible version, AWS environment variables, .boto profile, and AWS credeintials profile (~/.aws/config).

**Comment by decmaxn** [comment]
```
vma@Ubuntu1604:~$ ansible --version
ansible 2.3.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
vma@Ubuntu1604:~$ sudo find / -name boto.cfg
find: ‘/run/user/1000/gvfs’: Permission denied
vma@Ubuntu1604:~$ sudo find ~ -name .boto
vma@Ubuntu1604:~$ ll ~/.aws/config 
-rw------- 1 vma vma 106 Oct  3 20:44 /home/vma/.aws/config

vma@Ubuntu1604:~$ cat ~/.aws/config 
[default]
region=us-west-2
output = table
[profile victor]
region=us-west-2
output = table
#output = text

vma@Ubuntu1604:~$ cat ~/.aws/credentials 
[victor]
aws_access_key_id = VVVV-replaced-VVVVVVVV
aws_secret_access_key = VVVV-replaced-VVVVVVVV-password-VVVV

[default]
aws_access_key_id = DDDD-replaced-DDDDD
aws_secret_access_key = DDDD-replaced-DDDDD-password-DDDDDD
```

My command is:
`AWS_PROFILE=default ansible-playbook -i ../inventory/ec2.py --private-key=~/.ssh/key bastion.yml `

**Comment by bonovoxly** [comment]
So, the error:

```
Authorization header or parameters are not formatted correctly.
```

Seems to point to some misconfiguration of your AWS credentials. FYI, I've seen this error before when the AWS credentials are in your environment variables and they have newlines.. You may want to check that.

Another thing we can do is debug the AWS command.Can you edit the task and add the debug parameter to the AWS command?

```
- name: Add SSH public key to AWS System Log - this is BEST EFFORT.  May miss the SSH public key.
  shell: aws ec2 get-console-output \
           --debug \
           --region {{ vpc.region }} \
           --instance-id {{ item.id }} \
           --output text | sed -n 's/^.*\(ecdsa-sha2-nistp256 \)\(.*\)/\2/p' | tail -n 1 | awk '{print $1}' | awk '{print substr($0,1,140)}'
  register: host_key_results
  with_items: "{{ ec2_facts.instances }}"
```

We need to figure out where it's pulling AWS credentials and what they look like. Be wary, debug kicks out a ton of output. Here's the line we're interested in verifying:

```
2017-10-31 05:52:00,702 - MainThread - botocore.credentials - INFO - Found credentials in shared credentials file: ~/.aws/credentials
```

Need to figure out why the credentials within the Ansible playbook seems to fail. 🤔

**Comment by decmaxn** [comment]
I appologize that I have lost track of these issues, and kept them open for this long, appreciate all your help!
